### PR TITLE
Added app icons, updated the UI and fixed apps with no "CFBundleDisplayName".

### PR DESCRIPTION
**Pull request by ipodtouchdude**
* Added app icons.
* Updated the UI.
* Fixed apps with no "CFBundleDisplayName" showing up as something.app (Shows the real app name).

### CODE REVIEW

**Comment by ZonD80** [comment]
You need to add some kind of loading indicator (maybe popup), as app hangs on splash screen while it is enumerating through app directories to find icons (if you have lots of app installed). Please add it and submit PR again.

**Comment by ZonD80** [comment]
Update. It's better to check for CFBundleIcon in info.plist, rather than iterate through files. And it will speed up loading of an app.

**Comment by ipodtouchdude** [comment]
I've fixed the icon loading issue now and getting them from the info.plist. Just wondering which symbol do you like and I will change it to it. Then I will commit the files to GitHub and do another pull request. 
Image
Image
Image
Image

**Comment by ZonD80** [comment]
Thank you! One "!"
is enough I guess

**Comment by ipodtouchdude** [comment]
Was just about to edit the post and put this one.
Image

**Comment by ZonD80** [comment]
Cool! Ok

**Pull request merged**
